-- lv1 최댓값 구하기
SELECT MAX(DATETIME) AS 시간 FROM ANIMAL_INS

-- lv2 최솟값 구하기
SELECT MIN(DATETIME) AS 시간 FROM ANIMAL_INS

-- lv2 동물 수 구하기
SELECT COUNT(*) AS COUNT FROM ANIMAL_INS

-- lv2 중복 제거하기
SELECT COUNT(DISTINCT NAME) FROM ANIMAL_INS WHERE NAME IS NOT NULL