-- lv3 없어진 기록 찾기
SELECT A1.ANIMAL_ID, A1.NAME FROM ANIMAL_OUTS AS A1 LEFT OUTER JOIN ANIMAL_INS AS A2 ON A1.ANIMAL_ID = A2.ANIMAL_ID WHERE A2.ANIMAL_ID IS NULL ORDER BY ANIMAL_ID

-- lv3 있었는데요 없었습니다
SELECT A1.ANIMAL_ID, A1.NAME FROM ANIMAL_INS AS A1 INNER JOIN ANIMAL_OUTS AS A2 ON A1.ANIMAL_ID = A2.ANIMAL_ID WHERE A2.DATETIME < A1.DATETIME ORDER BY A1.DATETIME

-- lv3 오랜 기간 보호한 동물
SELECT A1.NAME, A1.DATETIME FROM ANIMAL_INS AS A1 LEFT OUTER JOIN ANIMAL_OUTS AS A2 ON A1.ANIMAL_ID = A2.ANIMAL_ID WHERE A2.ANIMAL_ID IS NULL ORDER BY DATETIME LIMIT 3

-- lv4 보호소에서 중성화한 동물
SELECT A1.ANIMAL_ID, A1.ANIMAL_TYPE, A1.NAME FROM ANIMAL_INS AS A1 INNER JOIN ANIMAL_OUTS AS A2 ON A1.ANIMAL_ID = A2.ANIMAL_ID WHERE A1.SEX_UPON_INTAKE != A2.SEX_UPON_OUTCOME ORDER BY A1.ANIMAL_ID