-- lv2 루시와 엘라 찾기
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE FROM ANIMAL_INS WHERE NAME IN ('Lucy', 'Ella', 'Pickle', 'Rogan', 'Sabrina', 'Mitty') ORDER BY ANIMAL_ID

-- lv2 이름에 el이 들어가는 동물 찾기
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE NAME LIKE "%EL%" AND ANIMAL_TYPE = 'Dog' ORDER BY NAME

-- lv2 중성화 여부 파악하기
SELECT ANIMAL_ID, NAME, IF(SEX_UPON_INTAKE REGEXP 'Neutered|Spayed', 'O', 'X') AS 중성화 FROM ANIMAL_INS ORDER BY ANIMAL_ID

-- lv3 오랜 기간 보호한 동물
SELECT A1.ANIMAL_ID, A1.NAME FROM ANIMAL_INS AS A1 INNER JOIN ANIMAL_OUTS AS A2 ON A1.ANIMAL_ID = A2.ANIMAL_ID ORDER BY (A2.DATETIME - A1.DATETIME) DESC LIMIT 2

-- lv2 DATETIME에서 DATE로 형 변환
SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME, "%Y-%m-%d") AS 날짜 FROM ANIMAL_INS